---
- name: Harden mongodb if detected
  when: mongodb_installed | default(false)
  block:
    - name: ensure mongod conf exists
      file:
        path: /etc/mongod.conf
        state: touch
    - name: set bindIp to localhost
      lineinfile:
        path: /etc/mongod.conf
        regexp: '^\s*bindIp:'
        line: '  bindIp: 127.0.0.1'
