version: '3.7'
services:
  wazuh:
    image: wazuh/wazuh:4.4.0_7.9.2
    container_name: wazuh-manager
    ports:
      - "1514:1514"
  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.4.0_7.9.2
    container_name: wazuh-dashboard
    ports:
      - "5601:5601"
